services:
  - type: web
    name: echomap-server
    runtime: docker
    plan: free
    repo: https://github.com/Sting421/Navigram_API.git  # Update this to your repo URL
    branch: main
    buildCommand: ./mvnw package -DskipTests
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://navigram-sting.k.aivencloud.com:19310/defaultdb?ssl-mode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_NlJLeYFcURhSVlM6sUO
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://echo-map-frontend.vercel.app,http://localhost:5173
      - key: AUTH0_DOMAIN
        value: dev-h8w5sjngzdjcyzsm.jp.auth0.com
      - key: AUTH0_CLIENT_ID
        value: cNk9rYMClfNS84GDSHIJYXi3J8wacU2R
      - key: AUTH0_AUDIENCE
        value: https://echomap-server.onrender.com/api
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -Dspring.profiles.active=prod"
