services:
  - type: web
    name: echomap-server
    runtime: docker
    plan: free
    repo: https://github.com/JivSTuban/EchoMapAPI.git
    branch: main
    buildCommand: cd EchoMapServer && ./mvnw package -DskipTests
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: echomap-db
          property: connectionString
          replacements:
            - from: postgres://
              to: jdbc:postgresql://
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: echomap-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: echomap-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://echo-map-frontend.vercel.app,http://localhost:5173
      - key: AUTH0_DOMAIN
        value: dev-h8w5sjngzdjcyzsm.jp.auth0.com
      - key: AUTH0_CLIENT_ID
        value: cNk9rYMClfNS84GDSHIJYXi3J8wacU2R
      - key: AUTH0_AUDIENCE
        value: https://echomap-server.onrender.com/api
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -Dspring.profiles.active=prod"

databases:
  - name: echomap-db
    plan: free
    databaseName: echomap
    ipAllowList: []  # Only allow connections from services within Render 